-- DW-EXIMIO-HML_PSO_ATENDIMENTO-INDICADORES-RETORNO-PRECOCE

WITH TAB_ATENDIMENTOS_PERIODO AS (
    SELECT * FROM VIEW_TAB_ATENDIMENTOS  
    WHERE SK_REDE_UNIDADE_SETOR = :HDATA_USUARIO_REDE_SETOR
		AND DT_ATENDIMENTO_INICIO::DATE BETWEEN :DT_ATENDIMENTO_MIN AND :DT_ATENDIMENTO_MAX
),
TAB_ATENDIMENTOS_FILTRADOS AS (
    SELECT * FROM VIEW_TAB_ATENDIMENTOS  
    WHERE SK_REDE_UNIDADE_SETOR = :HDATA_USUARIO_REDE_SETOR
		AND DT_ATENDIMENTO_INICIO::DATE BETWEEN :DT_ATENDIMENTO_MIN AND :DT_ATENDIMENTO_MAX
		AND CDE_CONVENIO = ANY(:CONVENIO) --OPTIONAL_FILTER
		AND CDE_CLASSIFICACAO_RISCO = ANY(:CLASSIFICACAO_RISCO) --OPTIONAL_FILTER
		AND CDE_ATENDIMENTO_ALTA_HOSPITALAR = ANY(:ATENDIMENTO_ALTA_HOSPITALAR) --OPTIONAL_FILTER
		AND SK_IDADE = ANY(:CODIGO_IDADE) --OPTIONAL_FILTER
		AND CDE_ESPECIALIDADE = ANY(:ESPECIALIDADE_ENTRADA) --OPTIONAL_FILTER
		AND CD_CID = ANY(:CID_ENTRADA) --OPTIONAL_FILTER
		AND DS_GRUPO_EPIDEMIOLOGICO = ANY(:GRUPO_EPIDEMIOLOGICO) --OPTIONAL_FILTER
		AND CDE_PRESTADOR = ANY(:PRESTADOR) --OPTIONAL_FILTER
		AND SN_HOUVE_INTERNACAO = ANY(:HOUVE_INTERNACAO) --OPTIONAL_FILTER
		AND SN_GRIPARIO = ANY(:GRIPARIO) --OPTIONAL_FILTER
		AND TP_EVASAO = ANY(:TIPO_EVASAO) --OPTIONAL_FILTER
		AND TP_CONVERSAO = ANY(:TIPO_CONVERSAO) --OPTIONAL_FILTER
        AND TP_TURNO = ANY(:TP_TURNO) --OPTIONAL_FILTER
        AND FAIXA_HORARIO = ANY(:FAIXA_TEMPO) --OPTIONAL_FILTER
        AND TP_DIA = ANY(:TP_DIA) --OPTIONAL_FILTER
        AND DIA_SEMANA = ANY(:DIA_SEMANA) --OPTIONAL_FILTER
	    AND TP_RETORNO = ANY(:TIPOS_DE_RETORNO) --OPTIONAL_FILTER
),
TAB_ATENDIMENTOS_PERIODO_COUNT AS (
    SELECT 
    	COUNT(DISTINCT CD_ATENDIMENTO) QTD_ATENDIMENTOS_GLOBAL,
    	SUM(
    		CASE
    			WHEN TP_ANALISE_RETORNO_PRECOCE = 'HOUVE_FALHA_ASSISTENCIAL' THEN 1 ELSE 0
    		END
    	) QTD_FALHAS_ASSISTENCIAIS_GLOBAL,
    	SN_SEG_EVASAO_PS,
    	SN_SEG_CONVERSAO_PS
    FROM TAB_ATENDIMENTOS_PERIODO
    GROUP BY 
    	SN_SEG_EVASAO_PS,
    	SN_SEG_CONVERSAO_PS
),
TAB_ATENDIMENTOS_FILTRADOS_COUNT AS (
    SELECT 
    	COUNT(DISTINCT CD_ATENDIMENTO) QTD_ATENDIMENTOS_FILTRO,
    	SUM(
    		CASE
    			WHEN TP_ANALISE_RETORNO_PRECOCE = 'HOUVE_FALHA_ASSISTENCIAL' THEN 1 ELSE 0
    		END
    	) QTD_FALHAS_ASSISTENCIAIS_FILTRO
	FROM TAB_ATENDIMENTOS_FILTRADOS
),
TAB_RETORNOS AS (
	SELECT
		COUNT(DISTINCT CD_ATENDIMENTO_INICIO) QTD_ATENDIMENTOS_RETORNO_GLOBAL,
		SUM(case 
			when TP_RETORNO IN ('24UI', '72UI') then 1 else 0
		end) QTD_ATENDIMENTOS_RETORNO_UI_GLOBAL,
		SUM(case 
			when TP_RETORNO IN ('24UTI', '72UTI') then 1 else 0
		end) QTD_ATENDIMENTOS_RETORNO_UTI_GLOBAL
	FROM TAB_ATENDIMENTOS_PERIODO
	WHERE TP_RETORNO IN ('24UI', '72UI', '24UTI', '72UTI', '24SEM', '72SEM')
	    AND CD_ATENDIMENTO_INICIO IS NOT NULL
),
TAB_RETORNOS_FILTRADOS AS (
	SELECT
		COUNT(DISTINCT CD_ATENDIMENTO_INICIO) QTD_ATENDIMENTOS_RETORNO_FILTRO,
		SUM(case 
			when TP_RETORNO IN ('24UI', '72UI') then 1 else 0
		end) QTD_ATENDIMENTOS_RETORNO_UI_FILTRO,
		SUM(case 
			when TP_RETORNO IN ('24UTI', '72UTI') then 1 else 0
		end) QTD_ATENDIMENTOS_RETORNO_UTI_FILTRO
	FROM TAB_ATENDIMENTOS_FILTRADOS
	WHERE TP_RETORNO IN ('24UI', '72UI', '24UTI', '72UTI', '24SEM', '72SEM')
	    AND CD_ATENDIMENTO_INICIO IS NOT NULL
),
TAB_ATENDIMENTOS_DATA_PERIODO AS (
    SELECT DISTINCT CONCAT(MIN(FA.DT_ATENDIMENTO_INICIO)::DATE, ' - ',
                       MAX(FA.DT_ATENDIMENTO_INICIO)::DATE) AS DS_PERIODO
	FROM FATO_ATENDIMENTO FA
	WHERE 
    	FA.DT_ATENDIMENTO_INICIO::DATE BETWEEN :DT_ATENDIMENTO_MIN::DATE AND :DT_ATENDIMENTO_MAX::DATE
		AND FA.SK_REDE_UNIDADE_SETOR = :HDATA_USUARIO_REDE_SETOR
),
TAB_META_INDICADOR AS (
	SELECT TIM.VL_META
	FROM TAB_INDICADOR_META TIM
	WHERE TIM.SK_REDE_UNIDADE_SETOR = :HDATA_USUARIO_REDE_SETOR
		AND :DT_ATENDIMENTO_MIN BETWEEN TIM.DT_VIGENCIA_INICIO::DATE AND TIM.DT_VIGENCIA_FIM::DATE
		AND TIM.SK_INDICADOR = 5
		AND TIM.TP_UTILIZACAO = 'OPERACIONAL'
		AND TIM.TP_INSERCAO = 'AUTOMATICO'
		AND TIM.METRICA = 'COM_INTERNACAO_GLOBAL'
		AND CDE_ESPECIALIDADE = ANY(:ESPECIALIDADE_ENTRADA) --OPTIONAL_FILTER
)
SELECT FA_DATA.DS_PERIODO,
       FA_PERIODO_1.QTD_ATENDIMENTOS_GLOBAL,
       coalesce(FAF.QTD_ATENDIMENTOS_FILTRO, 0) QTD_ATENDIMENTOS_FILTRO,
       coalesce(TR.QTD_ATENDIMENTOS_RETORNO_GLOBAL, 0) QTD_ATENDIMENTOS_RETORNO_GLOBAL,
       coalesce(TR.QTD_ATENDIMENTOS_RETORNO_UI_GLOBAL, 0) QTD_ATENDIMENTOS_RETORNO_UI_GLOBAL,
       coalesce(TR.QTD_ATENDIMENTOS_RETORNO_UTI_GLOBAL, 0) QTD_ATENDIMENTOS_RETORNO_UTI_GLOBAL,
       coalesce(TR.QTD_ATENDIMENTOS_RETORNO_UI_GLOBAL, 0) + coalesce(TR.QTD_ATENDIMENTOS_RETORNO_UTI_GLOBAL, 0) QTD_ATENDIMENTOS_RETORNO_INTERNACAO_GLOBAL,
       FA_PERIODO_1.QTD_FALHAS_ASSISTENCIAIS_GLOBAL,
       coalesce(TRF.QTD_ATENDIMENTOS_RETORNO_FILTRO, 0) QTD_ATENDIMENTOS_RETORNO_FILTRO,
       coalesce(TRF.QTD_ATENDIMENTOS_RETORNO_UI_FILTRO, 0) QTD_ATENDIMENTOS_RETORNO_UI_FILTRO,
       coalesce(TRF.QTD_ATENDIMENTOS_RETORNO_UTI_FILTRO, 0) QTD_ATENDIMENTOS_RETORNO_UTI_FILTRO,
       coalesce(TRF.QTD_ATENDIMENTOS_RETORNO_UI_FILTRO, 0) + coalesce(TRF.QTD_ATENDIMENTOS_RETORNO_UTI_FILTRO, 0) QTD_ATENDIMENTOS_RETORNO_INTERNACAO_FILTRO,
       coalesce(FAF.QTD_FALHAS_ASSISTENCIAIS_FILTRO, 0) QTD_FALHAS_ASSISTENCIAIS_FILTRO,
       ROUND((coalesce(TR.QTD_ATENDIMENTOS_RETORNO_GLOBAL, 0)::NUMERIC /
              FA_PERIODO_1.QTD_ATENDIMENTOS_GLOBAL::NUMERIC) * 100, 2) AS TX_ATENDIMENTOS_RETORNO_PRECOCE_GLOBAL,
       ROUND((coalesce(TR.QTD_ATENDIMENTOS_RETORNO_UI_GLOBAL, 0)::NUMERIC /
              FA_PERIODO_1.QTD_ATENDIMENTOS_GLOBAL::NUMERIC) * 100, 2) AS TX_ATENDIMENTOS_RETORNO_PRECOCE_UI_GLOBAL,
       ROUND((coalesce(TR.QTD_ATENDIMENTOS_RETORNO_UTI_GLOBAL, 0)::NUMERIC /
              FA_PERIODO_1.QTD_ATENDIMENTOS_GLOBAL::NUMERIC) * 100, 2) AS TX_ATENDIMENTOS_RETORNO_PRECOCE_UTI_GLOBAL,
       ROUND(((coalesce(TR.QTD_ATENDIMENTOS_RETORNO_UI_GLOBAL, 0)::numeric + coalesce(TR.QTD_ATENDIMENTOS_RETORNO_UTI_GLOBAL, 0)::numeric) /
              FA_PERIODO_1.QTD_ATENDIMENTOS_GLOBAL::NUMERIC) * 100, 2) AS TX_ATENDIMENTOS_RETORNO_PRECOCE_INTERNACAO_GLOBAL,
       ROUND((coalesce(FA_PERIODO_1.QTD_FALHAS_ASSISTENCIAIS_GLOBAL, 0)::NUMERIC /
              FA_PERIODO_1.QTD_ATENDIMENTOS_GLOBAL::NUMERIC) * 100, 2) AS TX_ATENDIMENTOS_FALHAS_ASSISTENCIAIS_GLOBAL,
       CASE
           WHEN FAF.QTD_ATENDIMENTOS_FILTRO > 0 THEN ROUND((coalesce(TRF.QTD_ATENDIMENTOS_RETORNO_FILTRO, 0)::NUMERIC /
                                                             FAF.QTD_ATENDIMENTOS_FILTRO::NUMERIC) * 100, 2)
           ELSE 0
       END TX_ATENDIMENTOS_RETORNO_PRECOCE_FILTRO,
       CASE
           WHEN FAF.QTD_ATENDIMENTOS_FILTRO > 0 THEN ROUND((coalesce(TRF.QTD_ATENDIMENTOS_RETORNO_UI_FILTRO, 0)::NUMERIC /
                                                            FAF.QTD_ATENDIMENTOS_FILTRO::NUMERIC) * 100, 2)
           ELSE 0
       END TX_ATENDIMENTOS_RETORNO_PRECOCE_UI_FILTRO,
       CASE
           WHEN FAF.QTD_ATENDIMENTOS_FILTRO > 0 THEN ROUND((coalesce(TRF.QTD_ATENDIMENTOS_RETORNO_UTI_FILTRO, 0)::NUMERIC /
                                                            FAF.QTD_ATENDIMENTOS_FILTRO::NUMERIC) * 100, 2)
           ELSE 0
       END TX_ATENDIMENTOS_RETORNO_PRECOCE_UTI_FILTRO,
       CASE
           WHEN FAF.QTD_ATENDIMENTOS_FILTRO > 0 THEN ROUND(((coalesce(TRF.QTD_ATENDIMENTOS_RETORNO_UI_FILTRO, 0)::numeric + coalesce(TRF.QTD_ATENDIMENTOS_RETORNO_UTI_FILTRO, 0)::numeric) /
                                                            FAF.QTD_ATENDIMENTOS_FILTRO::NUMERIC) * 100, 2)
           ELSE 0
       END TX_ATENDIMENTOS_RETORNO_PRECOCE_INTERNACAO_FILTRO,
       CASE
           WHEN FAF.QTD_ATENDIMENTOS_FILTRO > 0 THEN ROUND((coalesce(FAF.QTD_FALHAS_ASSISTENCIAIS_FILTRO, 0)::NUMERIC /
                                                            FAF.QTD_ATENDIMENTOS_FILTRO::NUMERIC) * 100, 2)
           ELSE 0
       END TX_ATENDIMENTOS_FALHAS_ASSISTENCIAIS_FILTRO,
	   TMI.VL_META TX_META_INDICADOR,
	   CASE 
	   		WHEN FAF.QTD_FALHAS_ASSISTENCIAIS_FILTRO = 0 THEN 'AUDITORIA PENDENTE'
	   		WHEN FAF.QTD_FALHAS_ASSISTENCIAIS_FILTRO = FAF.QTD_ATENDIMENTOS_FILTRO THEN 'AUDITORIA COMPLETA'
	   		ELSE 'AUDITORIA PARCIAL'
	   END STATUS_AUDITORIA,
       FA_PERIODO_1.SN_SEG_EVASAO_PS,
       FA_PERIODO_1.SN_SEG_CONVERSAO_PS
FROM TAB_ATENDIMENTOS_PERIODO_COUNT FA_PERIODO_1
	 LEFT JOIN TAB_ATENDIMENTOS_FILTRADOS_COUNT FAF ON TRUE
	 LEFT JOIN TAB_ATENDIMENTOS_DATA_PERIODO FA_DATA ON TRUE
	 LEFT JOIN TAB_RETORNOS TR ON TRUE
	 LEFT JOIN TAB_RETORNOS_FILTRADOS TRF ON TRUE
     LEFT JOIN TAB_META_INDICADOR TMI ON TRUE
WHERE FA_PERIODO_1.QTD_ATENDIMENTOS_GLOBAL > 0
;