-- DW-EXIMIO-HML_PSO_ATENDIMENTOS-POR-GRUPO-EPIDEMIOLOGICO

WITH TAB_ATENDIMENTOS_FILTRADOS AS (
    SELECT * FROM VIEW_TAB_ATENDIMENTOS  
    WHERE SK_REDE_UNIDADE_SETOR = :HDATA_USUARIO_REDE_SETOR
		AND DT_ATENDIMENTO_INICIO::DATE BETWEEN :DT_ATENDIMENTO_MIN AND :DT_ATENDIMENTO_MAX
		AND CDE_CONVENIO = ANY(:CONVENIO) --OPTIONAL_FILTER
		AND CDE_CLASSIFICACAO_RISCO = ANY(:CLASSIFICACAO_RISCO) --OPTIONAL_FILTER
		AND CDE_ATENDIMENTO_ALTA_HOSPITALAR = ANY(:ATENDIMENTO_ALTA_HOSPITALAR) --OPTIONAL_FILTER
		AND SK_IDADE = ANY(:CODIGO_IDADE) --OPTIONAL_FILTER
		AND CDE_ESPECIALIDADE = ANY(:ESPECIALIDADE_ENTRADA) --OPTIONAL_FILTER
		AND CD_CID = ANY(:CID_ENTRADA) --OPTIONAL_FILTER
		AND DS_GRUPO_EPIDEMIOLOGICO = ANY(:GRUPO_EPIDEMIOLOGICO) --OPTIONAL_FILTER
        AND CDE_PRESTADOR = ANY(:PRESTADOR) --OPTIONAL_FILTER
        AND SN_HOUVE_INTERNACAO = ANY(:HOUVE_INTERNACAO) --OPTIONAL_FILTER
        AND SN_GRIPARIO = ANY(:GRIPARIO) --OPTIONAL_FILTER
        AND TP_EVASAO = ANY(:TIPO_EVASAO) --OPTIONAL_FILTER
        AND TP_CONVERSAO = ANY(:TIPO_CONVERSAO) --OPTIONAL_FILTER
        AND TP_TURNO = ANY(:TP_TURNO) --OPTIONAL_FILTER
        AND FAIXA_HORARIO = ANY(:FAIXA_TEMPO) --OPTIONAL_FILTER
        AND TP_DIA = ANY(:TP_DIA) --OPTIONAL_FILTER
        AND DIA_SEMANA = ANY(:DIA_SEMANA) --OPTIONAL_FILTER
	    AND TP_RETORNO = ANY(:TIPOS_DE_RETORNO) --OPTIONAL_FILTER
),
TAB_ATENDIMENTOS_QTD AS (
    SELECT DISTINCT 
		DCC.DS_GRUPO_EPIDEMIOLOGICO,
        COUNT(FA.PK_ATENDIMENTO) OVER (PARTITION BY DCC.DS_GRUPO_EPIDEMIOLOGICO) QTD_ATENDIMENTOS_FILTRO,
        COUNT(FA.PK_ATENDIMENTO) OVER () QTD_ATENDIMENTOS_GLOBAL
    FROM TAB_ATENDIMENTOS_FILTRADOS FA
    LEFT JOIN DIM_CLASSIFICACAO_CID DCC ON
		DCC.CD_CID = FA.SK_CID_ENTRADA
),
TAB_ATENDIMENTOS_TX AS (
    SELECT
    	*,
    	ROUND( (QTD_ATENDIMENTOS_FILTRO::FLOAT/QTD_ATENDIMENTOS_GLOBAL::FLOAT)::NUMERIC * 100, 2) TX_ATENDIMENTOS_FILTRO
    FROM TAB_ATENDIMENTOS_QTD FA_QTD
)
SELECT
    *
FROM
    TAB_ATENDIMENTOS_TX
WHERE 
    DS_GRUPO_EPIDEMIOLOGICO IS NOT NULL
ORDER BY
    QTD_ATENDIMENTOS_FILTRO DESC
;